### ISSUE TITLE
R crash using primeFactorizeBig() and quadraticSieve()

### ISSUE THREAD

**Issue by JohannesFriedrich** [jwood000/RcppBigIntAlgos#2]
Using the function `primeFactorizeBig(12)` or `quadraticSieve(12)` (it doesn´t matter which number is the argument) crashes R as well as RStudio, see following screenshots.

![Bildschirmfoto 2020-12-13 um 21 56 53](https://user-images.githubusercontent.com/15369350/102023856-802cc480-3d8e-11eb-9c60-f30465b80cf0.png)

![Bildschirmfoto 2020-12-13 um 22 01 41](https://user-images.githubusercontent.com/15369350/102023914-d568d600-3d8e-11eb-90aa-42888969b270.png)

I´m using R 4.0.3 on macOS Catalina 10.15.7 but can´t use any function.

Any idea? I do not think this has to do with the new version 1.0 this was also a problem some days ago.
Thanks in advance!

**Comment by jwood000** [comment]
@JohannesFriedrich ,

Thanks for reporting. This is troubling indeed.

I am currently using R 4.0.3 on macOS Catalina 10.15.7 just like you and cannot reproduce. Are you getting the development version or downloading from CRAN? if you are building it yourself, make sure that you have `gmp` on your machine via:

```
brew install gmp
```

Also, do you have trouble with regular `gmp` functions like `factorize`?

Joseph

**Comment by JohannesFriedrich** [comment]
Hi, 
thanks for your fast answer! Yes gmp is installed via `brew`. I updated it to the newest version. Nevertheless, the same errors occur and you are right: I also have problems with the `gmp` package itself.

I uninstalled gmp via brew and also the R-package, installed all again but the error still occurs.

**Comment by JohannesFriedrich** [comment]
Hi again!

I solved the problem by cloning the repository of the original `gmp` R-project here:
https://forgemia.inra.fr/sylvain.jasson/gmp

I than built it on my own and now `RcppBigIntAlgos` and `gmp` are working fine!

**Comment by jwood000** [comment]
@JohannesFriedrich ,

This is great news. This will surely help future users.

Please don't hesitate bringing up any other issues moving forward.

Cheers,
Joseph
